repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.375
    hooks:
    - id: pyright
      additional_dependencies: [pydantic, xsdata, xsdata_pydantic, pint]
